### ISSUE TITLE
Email validation on contact form

### ISSUE THREAD

**Issue by rub1e** [fourloops/FourLoopsBlog#67]
Why did you choose `textarea` rather than `<input type=email>`?

**Comment by franzmoro** [comment]
@rub1e do you mean just changing the html tag, or properly validating the email address with javascript?

**Comment by rub1e** [comment]
just the tag

**Comment by franzmoro** [comment]
ok, thanks

**Comment by franzmoro** [comment]
The github page is not updated yet, but the html file was modified accordingly.

**Comment by rub1e** [comment]
That's fine, but you don't need to close the input tag

Otherwise happy to close
