### ISSUE TITLE
Tab consistency

### ISSUE THREAD

**Issue by Danwhy** [fourloops/FourLoopsBlog#68]
Your tab widths vary quite a bit, eg. [here](https://github.com/fourloops/FourLoopsBlog/blob/master/index.html#L29-L36) and [here](https://github.com/fourloops/FourLoopsBlog/blob/master/style.css#L301-L313). 

Make sure everyone in your team has the same tab width setting in their text editor. If you're using atom, in preferences, make sure soft tabs is on, and everyone has the same tab width set. This will make it much easier when you have lots of nested Javascript in the future.

**Comment by tu6619** [comment]
@Danwhy thanks for that, we may have had inconsistent tab width at the start of the project, now we've ensured consistency on that front and made sure that we all have soft tabs on.

**Comment by Danwhy** [comment]
Nice work. It took our group weeks just to agree on a tab width...
