### ISSUE TITLE
Slight tweaks for mobile fonts

### ISSUE THREAD

**Issue by andrewMacmurray** [fourloops/FourLoopsBlog#71]
Site looks great! Just might want to make the body font slightly bigger on mobile (maybe have the header fonts in a narrower desktop mode a little smaller too so they don't jump to the next line)

**Comment by tu6619** [comment]
Cheers mate, will bear your insightful comments in mind for next time!

**Comment by otajor** [comment]
@andrewMacmurray this has been done now, check out #91 for the changes :) also #78 made the social icons bigger on mobile :)

**Comment by andrewMacmurray** [comment]
:+1:
