### ISSUE TITLE
mobile content stays quite narrow

### ISSUE THREAD

**Issue by jay-meister** [fourloops/FourLoopsBlog#72]
Can increase the width for mobile view so the text fills the screen.

**Comment by tu6619** [comment]
OK cheers, will do mate.

**Comment by jay-meister** [comment]
@ me when done and i will close

**Comment by otajor** [comment]
@JMurphyWeb  this is done now, check out #91 for the changes :)

**Comment by jay-meister** [comment]
cool. 75% right?
