### ISSUE TITLE
Add comments to css files

### ISSUE THREAD

**Issue by katbow** [fourloops/FourLoopsBlog#75]
Clarify how different section of css apply to different sections of the site

**Comment by otajor** [comment]
Hmm this could be a long fix, our CSS is a mess. Will have a look and try to clean it up now.

**Comment by otajor** [comment]
OK wasn't too messy after all, but I linked to the wrong issue when I committed.

Here's the pull request that fixes this issue: https://github.com/fourloops/FourLoopsBlog/pull/82 @Katbow

**Comment by katbow** [comment]
Looks good! Thanks for the link
