### ISSUE TITLE
Tiny issue, js file

### ISSUE THREAD

**Issue by andrewMacmurray** [fourloops/FourLoopsBlog#77]
I know this is neither here nor there in this project (so you can ignore it if you like) but when we were looking at your files we immediately looked for a js file (and it's at the bottom of your html), might want to separate these out for readability.

**Comment by franzmoro** [comment]
thanks @andrewMacmurray, issue should now be solved (on local files, github page not updated yet)

**Comment by andrewMacmurray** [comment]
great
